# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Railroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='railroads', to='core.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_paths', to='core.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('entered_at', models.DateTimeField(null=True)),
                ('exited_at', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.Cluster')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='enter_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='exit_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='savedpath',
            name='station1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='savedpath',
            name='station2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='railroad',
            name='station1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_railroads', to='core.TrainStation'),
        ),
        migrations.AddField(
            model_name='railroad',
            name='station2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_railroads', to='core.TrainStation'),
        ),
    ]
